name: Daily Screener

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1-5'  # 09:00 UTC (17:00 Taipei)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run screener
        run: |
          python screener.py
      - name: Commit report
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.md'
          message: 'Add daily report'
